// PROPERTIES OF THE CHAIN DECODERS (server/chain/tx.js, server/chain/blockfile.js), over thousands of
// generated inputs rather than a handful of fixtures.
//
// Why this file exists next to chain-tx.test.js and chain-blockfile.test.js: those check the decoders
// against what Core said about REAL bytes, which is the strongest evidence for the bytes Core has
// actually produced -- and says nothing about the corners the chain has not visited yet (a script of
// exactly 0xfd bytes, an amount past 2^53 once compressed, a witness item of zero length in the
// middle of a stack) or about what the decoder does with bytes that are wrong. The address index is
// built from files on disk that can be half-written or damaged, so "throws a clear Error" versus
// "returns something plausible" is a real difference there.
//
// Everything here is generated by a small seeded PRNG written below (no libraries, Rule 1), so a
// failure prints its seed and case number and reproduces exactly. The oracles are written from the
// wire format and from Core's serialize.h / compressor.cpp, in BigInt where Core uses uint64, and are
// deliberately NOT the decoder's own helpers -- a property that checks a function against itself
// proves nothing.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { decodeTx, decodeBlock, classifyScript, Reader } from '../server/chain/tx.js';
import { unxor, records, decompressAmount, decodeBlockUndo, undoShape, MAGIC } from '../server/chain/blockfile.js';

// mulberry32: 32 good bits per draw. (blockpack.test.js's LCG is fine for sizes, but its low bits are
// weak, and these generators build u32 fields and random bytes out of the draws.)
function rng(seed) {
  let a = seed >>> 0;
  const next = () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const r = () => next();
  r.int = (lo, hi) => lo + Math.floor(next() * (hi - lo + 1));          // inclusive
  r.u32 = () => Math.floor(next() * 4294967296) >>> 0;
  r.u64 = () => (BigInt(r.u32()) << 32n) | BigInt(r.u32());
  r.bytes = (n) => { const b = Buffer.alloc(n); for (let i = 0; i < n; i++) b[i] = Math.floor(next() * 256); return b; };
  r.pick = (xs) => xs[Math.floor(next() * xs.length)];
  return r;
}

const sha256 = (b) => createHash('sha256').update(b).digest();
const dsha = (b) => sha256(sha256(b));
const revHex = (b) => Buffer.from(b).reverse().toString('hex');
const MAX_SAFE = BigInt(Number.MAX_SAFE_INTEGER);

// a synchronous decoder cannot be interrupted, so "never hang" is measured instead: every case is
// timed and the slowest one is held under a budget far above a linear decode of these sizes
const CASE_BUDGET_MS = 250;
function timed(fn) {
  const t0 = performance.now();
  let value, error, threw = false;
  try { value = fn(); } catch (e) { threw = true; error = e; }
  return { value, error, threw, ms: performance.now() - t0 };
}

// --- the wire format, written from the spec ------------------------------
// CompactSize: < 0xfd is one byte; 0xfd + u16; 0xfe + u32; 0xff + u64
function compactSize(n) {
  n = BigInt(n);
  if (n < 0xfdn) return Buffer.from([Number(n)]);
  if (n <= 0xffffn) { const b = Buffer.alloc(3); b[0] = 0xfd; b.writeUInt16LE(Number(n), 1); return b; }
  if (n <= 0xffffffffn) { const b = Buffer.alloc(5); b[0] = 0xfe; b.writeUInt32LE(Number(n), 1); return b; }
  const b = Buffer.alloc(9); b[0] = 0xff; b.writeBigUInt64LE(n, 1); return b;
}
const pushBytes = (b) => Buffer.concat([compactSize(b.length), b]);
const u32le = (v) => { const b = Buffer.alloc(4); b.writeUInt32LE(v >>> 0); return b; };
const i32le = (v) => { const b = Buffer.alloc(4); b.writeInt32LE(v | 0); return b; };
const u64le = (v) => { const b = Buffer.alloc(8); b.writeBigUInt64LE(BigInt(v)); return b; };

// a transaction as the generator holds it: { version, vin: [{ prev, vout, script, sequence, witness }],
// vout: [{ value, script }], locktime }. BIP144: with a witness, version | 00 01 | ins | outs |
// witness per input | locktime; without, version | ins | outs | locktime.
function serializeTx(tx, withWitness) {
  const parts = [i32le(tx.version)];
  if (withWitness) parts.push(Buffer.from([0x00, 0x01]));
  parts.push(compactSize(tx.vin.length));
  for (const i of tx.vin) parts.push(i.prev, u32le(i.vout), pushBytes(i.script), u32le(i.sequence));
  parts.push(compactSize(tx.vout.length));
  for (const o of tx.vout) parts.push(u64le(o.value), pushBytes(o.script));
  if (withWitness) for (const i of tx.vin) { parts.push(compactSize(i.witness.length)); for (const w of i.witness) parts.push(pushBytes(w)); }
  parts.push(u32le(tx.locktime));
  return Buffer.concat(parts);
}
const hasWitness = (tx) => tx.vin.some((i) => i.witness.length > 0);

// script lengths that sit on the CompactSize boundaries, plus ordinary ones
function scriptLen(r) {
  const p = r();
  if (p < 0.03) return r.pick([0xfc, 0xfd, 0xfe, 0xff, 0x100]);
  if (p < 0.035) return r.pick([0xffff, 0x10000]);
  if (p < 0.15) return 0;
  return r.int(1, 120);
}
function randomScript(r) {
  const p = r();
  const h20 = () => r.bytes(20), h32 = () => r.bytes(32);
  if (p < 0.1) return Buffer.concat([Buffer.from([0x76, 0xa9, 0x14]), h20(), Buffer.from([0x88, 0xac])]);   // p2pkh
  if (p < 0.2) return Buffer.concat([Buffer.from([0xa9, 0x14]), h20(), Buffer.from([0x87])]);                // p2sh
  if (p < 0.3) return Buffer.concat([Buffer.from([0x00, 0x14]), h20()]);                                     // p2wpkh
  if (p < 0.4) return Buffer.concat([Buffer.from([0x51, 0x20]), h32()]);                                     // taproot
  if (p < 0.45) return Buffer.concat([Buffer.from([0x6a]), pushBytes(r.bytes(r.int(0, 40)))]);             // OP_RETURN-ish
  return r.bytes(scriptLen(r));
}
function randomAmount(r) {
  const p = r();
  if (p < 0.1) return BigInt(r.pick([0, 1, 546, 2_100_000_000_000_000, Number.MAX_SAFE_INTEGER]));
  return BigInt(r.int(0, 2_100_000_000_000_000));
}
function randomTx(r, { segwit }) {
  // A LEGACY TRANSACTION NEEDS AT LEAST ONE INPUT: with none, its bytes begin version | 00 | ... and a
  // following output count of 1 reads as the BIP144 marker and flag. Core resolves that the same way
  // (it tries witness first), and a transaction with no inputs is invalid anyway.
  const nin = r() < 0.05 ? r.int(0xfd, 0x100) : r.int(1, 6);
  const nout = r() < 0.05 ? 0 : r() < 0.03 ? r.int(0xfd, 0x100) : r.int(1, 6);
  const vin = [];
  for (let i = 0; i < nin; i++) {
    const coinbase = i === 0 && r() < 0.1;
    const witness = [];
    if (segwit && r() < 0.8) {
      const items = r() < 0.02 ? 0xfd : r.int(1, 5);
      for (let k = 0; k < items; k++) witness.push(r() < 0.15 ? Buffer.alloc(0) : r.bytes(r() < 0.02 ? 0xfd : r.int(1, 80)));
    }
    vin.push({
      prev: coinbase ? Buffer.alloc(32) : r.bytes(32),
      vout: coinbase ? 0xffffffff : r.pick([0, 1, 2, 0xffffffff, r.u32()]),
      script: randomScript(r),
      sequence: r.pick([0xffffffff, 0xfffffffe, 0xfffffffd, 0, r.u32()]),
      witness,
    });
  }
  // BIP144 FORBIDS A WITNESS SERIALIZATION WITH NO WITNESS IN IT (Core: "Superfluous witness record"),
  // so a segwit transaction always carries at least one non-empty stack
  if (segwit && !hasWitness({ vin })) vin[r.int(0, nin - 1)].witness.push(r.bytes(r.int(0, 72)));
  const vout = Array.from({ length: nout }, () => ({ value: randomAmount(r), script: randomScript(r) }));
  return { version: r.pick([1, 2, 3, -1, 0x7fffffff, r.u32() | 0]), vin, vout, locktime: r.pick([0, 499_999_999, 500_000_000, r.u32()]) };
}

// The decoded shape back into the generator's form, so a decode can be re-serialized. Whether the
// decode was a witness serialization is read off weight: a legacy one weighs exactly size * 4.
function fromDecoded(d) {
  return {
    segwit: d.weight !== d.size * 4,
    tx: {
      version: d.version,
      vin: d.vin.map((i) => ({
        prev: i.coinbase != null ? Buffer.alloc(32) : Buffer.from(i.txid, 'hex').reverse(),
        vout: i.coinbase != null ? 0xffffffff : i.vout,
        script: Buffer.from(i.coinbase ?? i.scriptSig.hex, 'hex'),
        sequence: i.sequence,
        witness: (i.txinwitness ?? []).map((w) => Buffer.from(w, 'hex')),
      })),
      vout: d.vout.map((o) => ({ value: BigInt(o.value_sat), script: Buffer.from(o.scriptPubKey.hex, 'hex') })),
      locktime: d.locktime,
    },
  };
}

function assertDecodesAs(d, tx, segwit, at) {
  const base = serializeTx(tx, false), full = segwit ? serializeTx(tx, true) : base;
  assert.equal(d.txid, revHex(dsha(base)), `${at}: txid is double-SHA256 of the serialization WITHOUT witness`);
  assert.equal(d.hash, revHex(dsha(full)), `${at}: hash (wtxid) is double-SHA256 of the full serialization`);
  assert.equal(d.size, full.length, `${at}: size`);
  assert.equal(d.weight, base.length * 3 + full.length, `${at}: weight is base * 3 + total`);
  assert.equal(d.vsize, Math.ceil(d.weight / 4), `${at}: vsize`);
  assert.equal(d.version, tx.version, `${at}: version`);
  assert.equal(d.locktime, tx.locktime, `${at}: locktime`);
  assert.equal(d.vin.length, tx.vin.length, `${at}: input count`);
  tx.vin.forEach((w, i) => {
    const g = d.vin[i];
    const coinbase = w.vout === 0xffffffff && w.prev.every((b) => b === 0);
    if (coinbase) assert.equal(g.coinbase, w.script.toString('hex'), `${at}: vin ${i} coinbase script`);
    else {
      assert.equal(g.txid, revHex(w.prev), `${at}: vin ${i} txid is the outpoint hash, reversed`);
      assert.equal(g.vout, w.vout, `${at}: vin ${i} vout`);
      assert.equal(g.scriptSig.hex, w.script.toString('hex'), `${at}: vin ${i} scriptSig`);
    }
    assert.equal(g.sequence, w.sequence, `${at}: vin ${i} sequence`);
    // Core omits txinwitness for an empty stack; an empty ITEM inside a stack is still an item
    assert.deepEqual(g.txinwitness ?? [], w.witness.map((b) => b.toString('hex')), `${at}: vin ${i} witness`);
    if (!w.witness.length) assert.equal(g.txinwitness, undefined, `${at}: vin ${i} has no txinwitness key when the stack is empty`);
  });
  assert.equal(d.vout.length, tx.vout.length, `${at}: output count`);
  tx.vout.forEach((w, n) => {
    const g = d.vout[n];
    assert.equal(g.n, n, `${at}: vout ${n} index`);
    assert.equal(BigInt(g.value_sat), w.value, `${at}: vout ${n} value, to the satoshi`);
    assert.ok(Number.isSafeInteger(g.value_sat), `${at}: vout ${n} value is an exact integer`);
    assert.equal(g.scriptPubKey.hex, w.script.toString('hex'), `${at}: vout ${n} script`);
    const c = classifyScript(w.script);
    assert.equal(g.scriptPubKey.type, c.type, `${at}: vout ${n} type`);
    assert.equal(g.scriptPubKey.address, c.address ?? undefined, `${at}: vout ${n} address`);
  });
}

// --- CompactSize ----------------------------------------------------------
test('CompactSize: every boundary and 20,000 random values read back exactly, consuming exactly their encoding', () => {
  const r = rng(0xc0a1);
  const edges = [0n, 1n, 0xfcn, 0xfdn, 0xfen, 0xffn, 0x100n, 0xfffen, 0xffffn, 0x10000n, 0xfffffffen, 0xffffffffn, 0x100000000n, MAX_SAFE - 1n, MAX_SAFE];
  const values = [...edges];
  for (let i = 0; i < 20_000; i++) {
    const bits = r.int(0, 53);
    values.push(BigInt(Math.floor(r() * 2 ** bits)));
  }
  const width = (n) => (n < 0xfdn ? 1 : n <= 0xffffn ? 3 : n <= 0xffffffffn ? 5 : 9);
  for (const n of values) {
    const enc = compactSize(n);
    assert.equal(enc.length, width(n), `${n} encodes in ${width(n)} bytes`);
    const rd = new Reader(Buffer.concat([enc, Buffer.from([0xaa])]));
    assert.equal(rd.varint(), Number(n), `${n} reads back`);
    assert.equal(rd.pos, enc.length, `${n}: the reader stops right after the encoding`);
  }
  assert.equal(compactSize(0xfc)[0], 0xfc, '0xfc is still one byte');
  assert.deepEqual([...compactSize(0xfd)], [0xfd, 0xfd, 0x00], '0xfd itself needs the u16 form');
  // past 2^53 a JavaScript number cannot hold it: an error, never a rounded count
  for (const n of [MAX_SAFE + 1n, 0xffffffffffffffffn, r.u64() | (1n << 63n)]) {
    assert.throws(() => new Reader(compactSize(n)).varint(), RangeError, `${n} is refused, not rounded`);
  }
  // truncated at every byte of every width: an error, never a short read
  for (const n of [0xfdn, 0x10000n, 0x100000000n]) {
    const enc = compactSize(n);
    for (let cut = 0; cut < enc.length; cut++) assert.throws(() => new Reader(enc.subarray(0, cut)).varint(), RangeError, `${n} cut at ${cut}`);
  }
});

// --- Core's VARINT and CompressAmount, in the undo data ----------------------
// serialize.h WriteVarInt, in BigInt so the oracle is exact across all of uint64
function varInt(n) {
  n = BigInt(n);
  const tmp = [];
  for (let len = 0; ; len++) {
    tmp.push(Number((n & 0x7fn) | (len ? 0x80n : 0n)));
    if (n <= 0x7fn) break;
    n = (n >> 7n) - 1n;
  }
  return Buffer.from(tmp.reverse());
}
// compressor.cpp CompressAmount / DecompressAmount, in BigInt
function compressAmount(n) {
  n = BigInt(n);
  if (n === 0n) return 0n;
  let e = 0n;
  while (n % 10n === 0n && e < 9n) { n /= 10n; e++; }
  if (e < 9n) { const d = n % 10n; n /= 10n; return 1n + (n * 9n + d - 1n) * 10n + e; }
  return 1n + (n - 1n) * 10n + 9n;
}
function decompressAmountBig(x) {
  if (x === 0n) return 0n;
  x -= 1n;
  let e = x % 10n; x /= 10n;
  let n;
  if (e < 9n) { const d = (x % 9n) + 1n; x /= 9n; n = x * 10n + d; } else n = x + 1n;
  while (e > 0n) { n *= 10n; e--; }
  return n;
}

test('VARINT: the oracle writes serialize_tests.cpp\'s own vectors', () => {
  // (so the round trips below are against Core's encoding, not against a second copy of a mistake)
  for (const [n, hex] of [[0n, '00'], [0x7fn, '7f'], [0x80n, '8000'], [0x1234n, 'a334'], [0xffffn, '82fe7f'], [0x123456n, 'c7e756'],
    [0x80123456n, '86ffc7e756'], [0xffffffffn, '8efefefe7f'], [0x7fffffffffffffffn, 'fefefefefefefefe7f'], [0xffffffffffffffffn, '80fefefefefefefefe7f']]) {
    assert.equal(varInt(n).toString('hex'), hex, `VARINT(${n.toString(16)})`);
  }
  for (const [amount, c] of [[0n, 0n], [1n, 1n], [1_000_000n, 7n], [100_000_000n, 9n], [5_000_000_000n, 0x32n], [2_100_000_000_000_000n, 0x1406f40n]]) {
    assert.equal(compressAmount(amount), c, `CompressAmount(${amount})`);
    assert.equal(decompressAmountBig(c), amount);
  }
});

// one coin as Core's undo writer lays it out (undo.h TxInUndoFormatter): VARINT(height*2 + coinbase),
// a VARINT(0) version placeholder when height > 0, VARINT(CompressAmount(value)), then the script as
// VARINT(template or size + 6) and its bytes
function coinBytes({ height, coinbase, amountVarInt, scriptBytes }) {
  return Buffer.concat([varInt(BigInt(height) * 2n + (coinbase ? 1n : 0n)), ...(height > 0 ? [varInt(0)] : []), varInt(amountVarInt), scriptBytes]);
}
const rawScript = (s) => Buffer.concat([varInt(s.length + 6), s]);

test('CompressAmount: 50,000 amounts across 0..21e14 satoshis, and every edge, come back exact through the undo decoder', () => {
  const r = rng(0xa11);
  const amounts = [0n, 1n, 9n, 10n, 11n, 99n, 100n, 546n, 100_000_000n, 5_000_000_000n, 999_999_999_999_999n, 1_000_000_000_000_000n,
    1_000_000_000_000_001n, 2_099_999_999_999_999n, 2_100_000_000_000_000n, 2_099_999_999_999_990n, 1_234_567_890_123_457n, 1_999_999_999n];
  for (let i = 0; i < 50_000; i++) {
    const p = r();
    // plain uniform draws almost never end in zeros, and trailing zeros are what the exponent codes
    let a = p < 0.5 ? BigInt(r.int(0, 2_100_000_000_000_000)) : BigInt(r.int(0, 2_100_000)) * 10n ** BigInt(r.int(0, 9));
    if (a > 2_100_000_000_000_000n) a = 2_100_000_000_000_000n;
    amounts.push(a);
  }
  // the whole batch as one undo record, one coin per transaction, so the decoder reads 50,000 VARINTs
  const body = Buffer.concat([compactSize(amounts.length), ...amounts.map((a, i) => Buffer.concat([
    compactSize(1), coinBytes({ height: i, coinbase: false, amountVarInt: compressAmount(a), scriptBytes: rawScript(Buffer.from([0x51])) }),
  ]))]);
  const t0 = performance.now();
  const undo = decodeBlockUndo(body);
  const ms = performance.now() - t0;
  amounts.forEach((a, i) => {
    assert.equal(decompressAmountBig(compressAmount(a)), a, `the oracle round-trips ${a}`);
    assert.equal(undo[i][0].value_sat, Number(a), `amount ${a} (compressed ${compressAmount(a)}) decodes to the satoshi`);
    assert.equal(undo[i][0].height, i);
  });
  // THE BUG THIS FOUND: a compressed amount is about 9x the amount when it does not end in a zero, so
  // anything from ~1e15 satoshis up (10M BTC in one output, in range, if never seen) compresses past
  // 2^53, where Number arithmetic in readVarInt and decompressAmount rounds it. 2,099,999,999,999,999
  // came back as 209,999,999,999,999,940 before the fix: the rounding moved the exponent digit.
  assert.equal(decodeBlockUndo(Buffer.from('01010200a0c8adb1d183fe770751', 'hex'))[0][0].value_sat, 2_099_999_999_999_999,
    'regression: the exact undo bytes that decoded a hundred times too large');
  const worst = 2_099_999_999_999_999n;
  assert.ok(compressAmount(worst) > MAX_SAFE, 'the edge case really does compress past 2^53');
  assert.equal(decompressAmount(compressAmount(worst)), Number(worst), 'decompressAmount takes a BigInt and is exact past 2^53');
  assert.ok(ms < 2000, `50,000 coins decode in ${ms.toFixed(0)} ms`);
});

test('VARINT: 20,000 random uint64 amount fields decode exactly, or are refused when the value cannot be an exact number', () => {
  const r = rng(0x7a1);
  let exact = 0, refused = 0;
  const fields = [0n, 0x7fn, 0x80n, MAX_SAFE, MAX_SAFE + 1n, 0xffffffffffffffffn];
  for (let i = 0; i < 20_000; i++) fields.push(r.u64() >> BigInt(r.int(0, 63)));
  for (const x of fields) {
    const body = Buffer.concat([compactSize(1), compactSize(1), coinBytes({ height: 1, coinbase: true, amountVarInt: x, scriptBytes: rawScript(Buffer.alloc(0)) })]);
    const want = decompressAmountBig(x);
    const got = timed(() => decodeBlockUndo(body));
    if (want <= MAX_SAFE) {
      assert.equal(got.threw, false, `field ${x}: decodes (${got.error?.message})`);
      assert.equal(got.value[0][0].value_sat, Number(want), `field ${x} decompresses to ${want}`);
      exact++;
    } else {
      assert.ok(got.error instanceof RangeError, `field ${x} decompresses to ${want}, past 2^53: refused with a RangeError, not rounded`);
      refused++;
    }
  }
  assert.ok(exact > 1000 && refused > 1000, `both sides exercised (${exact} exact, ${refused} refused)`);
  // a VARINT wider than uint64 is corrupt (Core: "ReadVarInt(): size too large")
  const tooWide = Buffer.concat([compactSize(1), compactSize(1), varInt(3), varInt(0), Buffer.from('80fefefefefefefefeff00', 'hex'), rawScript(Buffer.alloc(0))]);
  assert.throws(() => decodeBlockUndo(tooWide), RangeError, 'past uint64');
  // the height code is uint32 in Core: a run of continuation bytes there used to decode as a height
  // of 7.6e22 -- the same unbounded read the undo byte-flip property caught as a value past 2^53
  assert.throws(() => decodeBlockUndo(Buffer.from('0101ffffffffffffffffffff0000090651', 'hex')), /VARINT too large/, 'a height code past uint32');
});

// secp256k1, for generating keys the compressed P2PK templates (4, 5) can carry
const P = 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2fn;
function modpow(b, e, m) { let x = 1n; b %= m; while (e > 0n) { if (e & 1n) x = (x * b) % m; b = (b * b) % m; e >>= 1n; } return x; }
function randomCurvePoint(r) {
  for (;;) {
    const x = BigInt('0x' + r.bytes(32).toString('hex')) % P;
    const rhs = (x ** 3n + 7n) % P;
    const y = modpow(rhs, (P + 1n) / 4n, P);
    if ((y * y) % P === rhs) return { x: Buffer.from(x.toString(16).padStart(64, '0'), 'hex'), y: Buffer.from((r() < 0.5 ? y : P - y).toString(16).padStart(64, '0'), 'hex') };
  }
}

// a random undo record: { body, want: [[{ height, coinbase, value_sat, script }]] }
function randomUndo(r) {
  const ntx = r() < 0.1 ? 0 : r.int(1, 6);
  const want = [], parts = [compactSize(ntx)];
  for (let t = 0; t < ntx; t++) {
    const nin = r.int(r() < 0.1 ? 0 : 1, 5);
    parts.push(compactSize(nin));
    const coins = [];
    for (let j = 0; j < nin; j++) {
      const height = r.pick([0, 1, 0x7f, 0x80, 900_000, 0x7fffffff, r.int(0, 1_000_000)]);
      const coinbase = r() < 0.2;
      const value = randomAmount(r);
      const kind = r.int(0, 6);
      let script, stored;
      if (kind === 0) { const h = r.bytes(20); script = Buffer.concat([Buffer.from([0x76, 0xa9, 0x14]), h, Buffer.from([0x88, 0xac])]); stored = Buffer.concat([varInt(0), h]); }
      else if (kind === 1) { const h = r.bytes(20); script = Buffer.concat([Buffer.from([0xa9, 0x14]), h, Buffer.from([0x87])]); stored = Buffer.concat([varInt(1), h]); }
      else if (kind === 2) { const k = 2 + r.int(0, 1), x = r.bytes(32); script = Buffer.concat([Buffer.from([0x21, k]), x, Buffer.from([0xac])]); stored = Buffer.concat([varInt(k), x]); }
      else if (kind === 3) {
        const { x, y } = randomCurvePoint(r);
        script = Buffer.concat([Buffer.from([0x41, 0x04]), x, y, Buffer.from([0xac])]);
        stored = Buffer.concat([varInt(4 + (y[31] & 1)), x]);
      } else { script = r.bytes(scriptLen(r)); stored = rawScript(script); }
      parts.push(coinBytes({ height, coinbase, amountVarInt: compressAmount(value), scriptBytes: stored }));
      coins.push({ height, coinbase, value_sat: Number(value), script });
    }
    want.push(coins);
  }
  return { body: Buffer.concat(parts), want };
}

test('undo records: 2,000 random records decode every coin exactly, and undoShape agrees', () => {
  const r = rng(0x0d0);
  let coins = 0;
  for (let c = 0; c < 2000; c++) {
    const { body, want } = randomUndo(r);
    const got = decodeBlockUndo(body);
    assert.deepEqual(undoShape(body), want.map((t) => t.length), `case ${c}: shape`);
    assert.equal(got.length, want.length, `case ${c}: transaction count`);
    want.forEach((coinsW, t) => coinsW.forEach((w, j) => {
      const g = got[t][j], at = `case ${c} tx ${t} coin ${j}`;
      assert.equal(g.height, w.height, `${at}: height`);
      assert.equal(g.coinbase, w.coinbase, `${at}: coinbase flag`);
      assert.equal(g.value_sat, w.value_sat, `${at}: value`);
      assert.equal(g.script.toString('hex'), w.script.toString('hex'), `${at}: script (including a 65-byte key rebuilt from the curve)`);
      coins++;
    }));
  }
  assert.ok(coins > 10_000, `${coins} coins checked`);
});

test('undo records: truncated at every byte offset, both readers throw an Error -- never a shorter record', () => {
  // THE BUG THIS FOUND: undoShape skips script bytes by moving its position and never looked at where
  // it ended, so a record cut in the middle of a script returned the full input counts, as if whole.
  // It is what pairs undo records with blocks, so a half-written rev file could shape-match. And
  // decodeBlockUndo's take() sliced past the end silently, only failing later with "-N bytes left".
  const r = rng(0x7c);
  let cuts = 0, slowest = 0;
  for (let c = 0; c < 80; c++) {
    const { body } = randomUndo(r);
    if (body.length > 2000) { c--; continue; }          // a 64 KB script makes the every-offset sweep quadratic
    for (let cut = 0; cut < body.length; cut++) {
      const part = body.subarray(0, cut);
      for (const [name, fn] of [['decodeBlockUndo', decodeBlockUndo], ['undoShape', undoShape]]) {
        const got = timed(() => fn(part));
        slowest = Math.max(slowest, got.ms);
        assert.ok(got.threw, `case ${c}: ${name} on the first ${cut} of ${body.length} bytes must throw (returned ${JSON.stringify(got.value)?.slice(0, 80)})`);
        assert.ok(got.error instanceof Error, `case ${c}: ${name} cut at ${cut} throws an Error, not ${String(got.error)}`);
      }
      cuts++;
    }
  }
  assert.ok(slowest < CASE_BUDGET_MS, `every truncation answered promptly (slowest ${slowest.toFixed(1)} ms over ${cuts} cuts)`);
  // regression: one coin with a 10-byte raw script, cut 3 bytes short. undoShape returned [1].
  const cutShort = Buffer.from('01010200091000000000000000', 'hex');
  assert.throws(() => undoShape(cutShort), /truncated undo record/, 'undoShape refuses a record cut inside its last script');
  assert.throws(() => decodeBlockUndo(cutShort), /truncated script/, 'and decodeBlockUndo says where, not "-3 bytes left"');
});

test('undo records: random byte flips either throw an Error or decode to well-formed coins both readers agree on', () => {
  const r = rng(0xf11b);
  let threw = 0, decoded = 0, slowest = 0;
  for (let c = 0; c < 5000; c++) {
    const { body } = randomUndo(r);
    if (!body.length) continue;
    const bad = Buffer.from(body);
    for (let k = r.int(1, 3); k > 0; k--) bad[r.int(0, bad.length - 1)] ^= r.int(1, 255);
    const full = timed(() => decodeBlockUndo(bad)), shape = timed(() => undoShape(bad));
    slowest = Math.max(slowest, full.ms, shape.ms);
    for (const g of [full, shape]) if (g.threw) assert.ok(g.error instanceof Error, `case ${c}: throws an Error, not ${String(g.error)}`);
    if (full.threw) { threw++; continue; }
    decoded++;
    assert.equal(shape.threw, false, `case ${c}: decodeBlockUndo accepted it, so undoShape must too (${shape.error?.message})`);
    assert.deepEqual(shape.value, full.value.map((t) => t.length), `case ${c}: and they agree on its shape`);
    for (const coin of full.value.flat()) {
      assert.ok(Number.isSafeInteger(coin.height) && coin.height >= 0, `case ${c}: height ${coin.height} is an exact integer`);
      assert.ok(Number.isSafeInteger(coin.value_sat) && coin.value_sat >= 0, `case ${c}: value ${coin.value_sat} is an exact integer`);
      assert.ok(Buffer.isBuffer(coin.script), `case ${c}: script is bytes`);
    }
  }
  assert.ok(threw > 500 && decoded > 50, `both outcomes exercised (${threw} threw, ${decoded} decoded)`);
  assert.ok(slowest < CASE_BUDGET_MS, `slowest case ${slowest.toFixed(1)} ms`);
});

// --- transactions -----------------------------------------------------------
test('transactions: 3,000 random legacy and segwit transactions decode to exactly the fields they were built from', () => {
  const r = rng(0x7e5);
  const seen = { legacy: 0, segwit: 0, coinbase: 0, emptyItem: 0, bigCount: 0, noOutputs: 0 };
  for (let c = 0; c < 3000; c++) {
    const segwit = r() < 0.5;
    const tx = randomTx(r, { segwit });
    const bytes = serializeTx(tx, segwit);
    const at = `case ${c} (${segwit ? 'segwit' : 'legacy'})`;
    const d = decodeTx(bytes);
    assertDecodesAs(d, tx, segwit, at);
    assert.equal(decodeTx(bytes.toString('hex')).hash, d.hash, `${at}: hex and Buffer input agree`);
    seen[segwit ? 'segwit' : 'legacy']++;
    if (d.vin[0]?.coinbase != null) seen.coinbase++;
    if (tx.vin.some((i) => i.witness.some((w) => !w.length))) seen.emptyItem++;
    if (tx.vin.length >= 0xfd || tx.vout.length >= 0xfd || tx.vin.some((i) => i.script.length >= 0xfd)) seen.bigCount++;
    if (!tx.vout.length) seen.noOutputs++;
  }
  for (const [k, n] of Object.entries(seen)) assert.ok(n > 20, `the generator covered ${k} (${n} cases)`);
});

test('transactions: truncated at every byte offset, decoding throws an Error -- never a partial transaction', () => {
  const r = rng(0x7c7);
  let cuts = 0, slowest = 0;
  for (let c = 0; c < 400; c++) {
    const segwit = r() < 0.5;
    const tx = randomTx(r, { segwit });
    const bytes = serializeTx(tx, segwit);
    if (bytes.length > 4000) { c--; continue; }         // keep the quadratic sweep to seconds
    for (let cut = 0; cut < bytes.length; cut++) {
      const got = timed(() => decodeTx(bytes.subarray(0, cut)));
      slowest = Math.max(slowest, got.ms);
      assert.ok(got.threw, `case ${c}: the first ${cut} of ${bytes.length} bytes decoded (${got.value?.txid})`);
      assert.ok(got.error instanceof Error, `case ${c} cut ${cut}: an Error, not ${String(got.error)}`);
      assert.match(got.error.message, /truncated/, `case ${c} cut ${cut}: says so`);
      cuts++;
    }
  }
  assert.ok(cuts > 50_000, `${cuts} truncations`);
  assert.ok(slowest < CASE_BUDGET_MS, `slowest ${slowest.toFixed(1)} ms`);
});

test('transactions: random byte flips either throw an Error or decode to a transaction that re-serializes to exactly those bytes', () => {
  // "re-serializes to exactly those bytes" is the strong form of "no partial object": every byte was
  // read, into the field it belongs to, and nothing was skipped, rounded or guessed
  const r = rng(0xf1f);
  let threw = 0, decoded = 0, slowest = 0;
  const reasons = new Map();
  for (let c = 0; c < 20_000; c++) {
    const segwit = r() < 0.5;
    const tx = randomTx(r, { segwit });
    const bytes = serializeTx(tx, segwit);
    if (bytes.length > 3000) continue;
    const bad = Buffer.from(bytes);
    // bias toward the structural bytes at the front, where a flip changes how the rest is framed
    for (let k = r.int(1, 3); k > 0; k--) bad[r() < 0.5 ? r.int(0, Math.min(bad.length - 1, 60)) : r.int(0, bad.length - 1)] ^= r() < 0.3 ? 1 << r.int(0, 7) : r.int(1, 255);
    const got = timed(() => decodeTx(bad));
    slowest = Math.max(slowest, got.ms);
    if (got.threw) {
      assert.ok(got.error instanceof Error, `case ${c}: an Error, not ${String(got.error)}`);
      const why = got.error.message.replace(/[0-9]+/g, 'N');
      reasons.set(why, (reasons.get(why) ?? 0) + 1);
      threw++;
      continue;
    }
    decoded++;
    const back = fromDecoded(got.value);
    assert.ok(serializeTx(back.tx, back.segwit).equals(bad), `case ${c}: decoded bytes ${bad.toString('hex').slice(0, 80)}... re-serialize identically`);
    assert.equal(got.value.hash, revHex(dsha(bad)), `case ${c}: the wtxid is of the bytes given`);
  }
  assert.ok(threw > 1000 && decoded > 1000, `both outcomes exercised (${threw} threw, ${decoded} decoded)`);
  assert.ok(slowest < CASE_BUDGET_MS, `slowest ${slowest.toFixed(1)} ms`);
});

// --- blocks and the files they live in ----------------------------------------
test('blocks: 300 random blocks decode their header and every transaction, and fail on any truncation', () => {
  const r = rng(0xb10c);
  for (let c = 0; c < 300; c++) {
    const header = Buffer.concat([i32le(r.u32() | 0), r.bytes(32), r.bytes(32), u32le(r.u32()), u32le(r.u32()), u32le(r.u32())]);
    const txs = Array.from({ length: r() < 0.02 ? 0xfd : r.int(1, 8) }, () => { const segwit = r() < 0.5; return { segwit, tx: randomTx(r, { segwit }) }; });
    const block = Buffer.concat([header, compactSize(txs.length), ...txs.map((t) => serializeTx(t.tx, t.segwit))]);
    const d = decodeBlock(block);
    assert.equal(d.hash, revHex(dsha(header)), `block ${c}: hash of the 80-byte header`);
    assert.equal(d.previousblockhash, revHex(header.subarray(4, 36)), `block ${c}: previous hash`);
    assert.equal(d.merkleroot, revHex(header.subarray(36, 68)), `block ${c}: merkle root field`);
    assert.equal(d.nonce, header.readUInt32LE(76), `block ${c}: nonce`);
    assert.equal(d.nTx, txs.length);
    assert.equal(d.size, block.length);
    txs.forEach((t, i) => assertDecodesAs(d.tx[i], t.tx, t.segwit, `block ${c} tx ${i}`));
    for (let k = 0; k < 20; k++) {
      const cut = r.int(0, block.length - 1);
      assert.throws(() => decodeBlock(block.subarray(0, cut)), /truncated/, `block ${c} cut at ${cut}`);
    }
  }
});

test('blk/rev files: XOR is its own inverse at any offset, and framing a file cut anywhere yields exactly its whole records', () => {
  const r = rng(0xf11e);
  const nets = Object.values(MAGIC);
  for (let c = 0; c < 200; c++) {
    const key = r() < 0.2 ? Buffer.alloc(8) : r.bytes(8);
    const magic = r.pick(nets), trailer = r() < 0.5 ? 32 : 0;
    const bodies = Array.from({ length: r.int(0, 5) }, () => r.bytes(r.int(1, 300)));
    const frames = bodies.map((b) => { const h = Buffer.alloc(8); h.writeUInt32LE(magic, 0); h.writeUInt32LE(b.length, 4); return Buffer.concat([h, b, r.bytes(trailer)]); });
    const plain = Buffer.concat([...frames, r() < 0.5 ? Buffer.alloc(r.int(0, 64)) : Buffer.alloc(0)]);
    const disk = unxor(Buffer.from(plain), key, 0);
    // XOR by absolute offset: de-obfuscating any slice on its own agrees with the whole file
    const off = r.int(0, plain.length), len = r.int(0, plain.length - off);
    assert.ok(unxor(Buffer.from(disk.subarray(off, off + len)), key, off).equals(plain.subarray(off, off + len)), `case ${c}: a slice at ${off} unxors on its own`);
    assert.ok(unxor(unxor(Buffer.from(plain), key, 7), key, 7).equals(plain), `case ${c}: unxor twice is the identity`);
    // cut the file anywhere, as the last file is while Core appends: only whole records come out
    const ends = []; let pos = 0;
    for (const f of frames) { pos += f.length; ends.push(pos); }
    for (let cut = 0; cut <= plain.length; cut += r.int(1, 17)) {
      const got = [...records(plain.subarray(0, cut), magic, trailer)];
      const whole = ends.filter((e) => e <= cut).length;
      assert.equal(got.length, whole, `case ${c}: a file cut at ${cut} holds ${whole} whole records`);
      got.forEach((g, i) => assert.ok(g.body.equals(bodies[i]), `case ${c}: record ${i} body`));
    }
  }
});
