// Drill-down, multi-node, and the TLS decision.
//
// The drill-down endpoints exist because "which transaction?" had one answer in this
// app: type an RPC into the console. What constrains them is the node: verbosity 2
// costs ~11 MB of hex per block (MEASUREMENTS §6) on a server that services one
// connection at a time, so these routes ask for verbosity 1 and getblockstats, and
// say what they refused to report rather than inventing the missing field.
//
// The fake node deliberately REFUSES verbosity 2, which is what turns "the monitor
// never asks" from an intention into an assertion.
import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { withApp } from './helpers/http.js';

// The bootstrap admin's password is generated by boot() and read back off
// app.bootstrap -- no shared secret through process.env (see helpers/http.js).
// Declared per test via client.adminPassword.

test('a block can be inspected by height, and reports header + stats + txids', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    const state = await client.get('/api/state?series=none');
    const tip = state.body.tip.height;
    assert.ok(tip > 0, 'the fake node has a chain');

    const r = await client.get(`/api/block?height=${tip}`);
    assert.equal(r.status, 200);
    assert.equal(r.body.ok, true, JSON.stringify(r.body));
    assert.equal(r.body.header.height, tip);
    assert.match(r.body.header.hash, /^[0-9a-f]{64}$/);
    assert.ok(r.body.header.nTx >= 1, 'the block has transactions');
    assert.ok(r.body.stats, 'getblockstats came back (fees without fetching every tx)');
    assert.ok(r.body.stats.totalfee >= 0);
    assert.ok(r.body.txids.length >= 1 && r.body.txids.length <= 50, 'a page of txids, not the whole block');
    assert.equal(r.body.txidsTotal, r.body.header.nTx);
    assert.ok(r.body.notes.some((n) => /verbosity=2/.test(n)), 'the route says why it stopped at verbosity 1');
  });
});

test('a block can be inspected by hash, and a bad input is refused with a reason', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    const tip = (await client.get('/api/state?series=none')).body.tip.height;
    const byHeight = await client.get(`/api/block?height=${tip}`);
    const hash = byHeight.body.header.hash;

    const byHash = await client.get(`/api/block?hash=${hash}`);
    assert.equal(byHash.body.ok, true);
    assert.equal(byHash.body.header.hash, hash, 'the same block by the other route');

    const badHash = await client.get('/api/block?hash=zzz');
    assert.equal(badHash.status, 400, 'a malformed hash is our error, not the node\'s');
    assert.match(badHash.body.error.message, /64-hex/);

    const badHeight = await client.get('/api/block?height=-4');
    assert.equal(badHeight.status, 400);

    const noBlock = await client.get(`/api/block?hash=${'00'.repeat(32)}`);
    assert.equal(noBlock.status, 200, 'the node\'s own "not found" is data, so it is passed through at 200');
    assert.equal(noBlock.body.ok, false);
    assert.match(noBlock.body.error.message, /not found/i);
  });
});

test('the monitor never asks for getblock verbosity 2 (the fake node refuses it)', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    const tip = (await client.get('/api/state?series=none')).body.tip.height;
    const r = await client.get(`/api/block?height=${tip}`);
    assert.equal(r.body.ok, true, 'if verbosity 2 had been asked for, the fake would have refused and ok would be false');
    assert.ok(!JSON.stringify(r.body).includes('is not simulated'), 'the refusal text never reaches the client');
  });
});

test('a transaction decodes, and the fee it cannot have is named rather than guessed', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    // Reached through a block rather than the pool: the fake's pool entries churn
    // every tick, and a confirmed txid is stable long enough to assert against.
    const tip = (await client.get('/api/state?series=none')).body.tip.height;
    const block = await client.get(`/api/block?height=${tip}`);
    const one = block.body.txids[3] ?? block.body.txids[0];
    const r = await client.get(`/api/tx?txid=${one}&block=${block.body.header.hash}`);
    assert.equal(r.status, 200);
    assert.equal(r.body.ok, true, JSON.stringify(r.body));
    assert.equal(r.body.txid, one);
    assert.ok(r.body.inputs.length >= 1 && r.body.outputs.length >= 1);
    assert.ok(r.body.confirmations >= 1);
    assert.ok(r.body.totalOutSat > 0, 'outputs summed in satoshis, not floats');
    assert.ok(r.body.notReported.some((n) => /fee/i.test(n)),
      'the fee is absent and says why: computing it needs every input\'s prevout, on a one-threaded RPC server');

    const badTx = await client.get('/api/tx?txid=abc');
    assert.equal(badTx.status, 400);
    const missing = await client.get(`/api/tx?txid=${'11'.repeat(32)}`);
    assert.equal(missing.body.ok, false);
    assert.match(missing.body.error.message, /not found/i);
    assert.match(missing.body.hint ?? '', /block/, 'the hint says what to add when a tx has left the pool');
  });
});

test('two nodes are both monitored, named, and kept apart', async () => {
  await withApp({ nodes: 2 }, async ({ client, app }) => {
    await client.login('admin');
    const nodes = await client.get('/api/nodes');
    assert.equal(nodes.body.nodes.length, 2, 'both configured nodes are live');
    const ids = nodes.body.nodes.map((n) => n.id).sort();
    assert.deepEqual(ids, ['node-1', 'node-a']);

    // Every node answers for itself. The measured failure this guards: one `peers`
    // ring holding 2,308 production rows and 1,816 bench rows, drawn as one line.
    const a = await client.get('/api/state?node=node-a&series=none');
    const b = await client.get('/api/state?node=node-1&series=none');
    assert.equal(a.body.id, 'node-a');
    assert.equal(b.body.id, 'node-1');
    assert.equal(a.body.sync.node, 'node-a', 'the sync bar carries its node inside it');
    assert.equal(b.body.sync.node, 'node-1');
    assert.notEqual(a.body.label, b.body.label, 'and says which one it is on screen');

    // Optional nodes degrade to a note, not a red app. node-1 is marked optional in
    // the test config; both are up here, so `ok` must be true either way.
    const health = await client.get('/api/health');
    assert.equal(health.body.ok, true);
    assert.deepEqual(health.body.degraded, []);

    // An unknown node on the stream is refused rather than streaming silence.
    const stream = await client.raw('/api/stream?node=who');
    assert.equal(stream.status, 404);
    assert.equal((await stream.json()).error.kind, 'unknown_node');

    assert.equal(app.monitors.size, 2);
  });
});

test('the mempool page says it is a poll, not a transaction stream', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    const mp = await client.get('/api/mempool');
    assert.equal(mp.body.feed.kind, 'poll');
    assert.equal(mp.body.feed.streamAvailable, false, 'the node refuses zmqpubsequence; the UI must not imply per-tx events');
    assert.match(mp.body.feed.why, /removed/, 'and the reason names the missing choke point');
  });
});

test('the audit endpoint reports the size of the trail it is reading', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    await client.get('/api/health');
    const r = await client.get('/api/audit?limit=5');
    assert.equal(r.status, 200);
    const log = r.body.log;
    assert.ok(log.maxBytes >= 65536);
    assert.ok(log.currentBytes > 0, 'entries were written during this boot, so the file is not empty');
    assert.ok(log.headroomBytes <= log.maxBytes);
    assert.equal(log.rotationError, null, 'nothing failed to rotate in a test this short');
  });
});

test('telemetry carries the breaker state that made a 2026-09-08 flap unanswerable', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    const t = await client.get('/api/telemetry');
    const b = t.body.nodes[0].rpc.breaker;
    assert.equal(b.open, false);
    assert.equal(b.threshold, 3);
    assert.equal(typeof b.cooldownMs, 'number');
    assert.equal(b.consecutive, 0, 'a healthy lane says so with a number, not an absence');
    assert.ok(t.body.audit, 'audit size is on the telemetry page too');
  });
});
