// The feerate palette: our own bands, generated by a formula, and our own
// colour ramp from sky blue through teal, green, yellow, orange and red to purple.
// Two neighbouring bands must be told apart at a glance: at least this far apart in RGB.
import test from 'node:test';
import assert from 'node:assert/strict';
import { FEE_BANDS, feeBandIndex, feeColor, feeShade } from '../public/js/feepalette.js';

const rgbOf = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
function hueOf(hex) {
  const [r, g, b] = rgbOf(hex).map((v) => v / 255);
  const mx = Math.max(r, g, b), mn = Math.min(r, g, b), d = mx - mn;
  if (d === 0) return 0;
  const h = mx === r ? ((g - b) / d) % 6 : mx === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return (h * 60 + 360) % 360;
}
const MIN_NEIGHBOUR = 16;
const luma = (hex) => { const [r, g, b] = rgbOf(hex); return 0.2126 * r + 0.7152 * g + 0.0722 * b; };

test('the bands: 128 of them, 0 then 0.1 up to 2000 sat/vB, ascending', () => {
  assert.equal(FEE_BANDS.length, 128);
  assert.equal(FEE_BANDS[0], 0);
  assert.equal(FEE_BANDS[1], 0.1, 'band 1 starts at 0.1 sat/vB: this chain\'s blocks go that low');
  assert.equal(FEE_BANDS.at(-1), 2000);
  for (let i = 1; i < FEE_BANDS.length; i++) assert.ok(FEE_BANDS[i] > FEE_BANDS[i - 1], `ascending at ${i}`);
  assert.ok(Object.isFrozen(FEE_BANDS), 'nobody can edit the bands at runtime');
});

test('the bands are a geometric series: close together near the floor, far apart near the ceiling', () => {
  assert.ok(FEE_BANDS.filter((b) => b >= 0.1 && b < 1).length >= 28, 'dozens of bands below 1 sat/vB');
  assert.ok(FEE_BANDS.filter((b) => b >= 0.1 && b <= 30).length >= 70, '0.1..30 sat/vB, where this chain lives, spans 70+ bands');
  // every step is roughly the same ratio (two-figure rounding aside)
  const ratios = FEE_BANDS.slice(2).map((b, i) => b / FEE_BANDS[i + 1]);
  const mean = ratios.reduce((a, r) => a + r, 0) / ratios.length;
  for (const r of ratios) assert.ok(Math.abs(r / mean - 1) < 0.2, `ratio ${r.toFixed(3)} near the mean ${mean.toFixed(3)}`);
  const gaps = FEE_BANDS.slice(1).map((b, i) => b - FEE_BANDS[i]);
  assert.ok(gaps.at(-1) > 1000 * gaps[1], 'the ceiling gaps are far wider than the floor gaps');
  // readable numbers: two significant figures, three only where two would repeat the band below
  for (const b of FEE_BANDS.slice(1)) assert.equal(Number(b.toPrecision(3)), b, `${b} has at most three figures`);
  const three = FEE_BANDS.slice(1).filter((b) => Number(b.toPrecision(2)) !== b);
  assert.ok(three.length < 20, `${three.length} three-figure thresholds (${three.join(' ')})`);
});

test('128 separate colours: neighbours differ in hue and in tone', () => {
  const colors = FEE_BANDS.map((b) => feeColor(b));
  assert.equal(new Set(colors).size, 128, `${new Set(colors).size} distinct colours`);
  const dist = (a, b) => Math.hypot(...rgbOf(a).map((v, i) => v - rgbOf(b)[i]));
  for (let i = 1; i < colors.length; i++) {
    assert.ok(dist(colors[i], colors[i - 1]) >= MIN_NEIGHBOUR, `bands ${i - 1} and ${i}: ${colors[i - 1]} vs ${colors[i]} too close (${dist(colors[i], colors[i - 1]).toFixed(1)})`);
  }
  // a block that runs 0.1..30 sat/vB shows dozens of colours, not one
  const live = new Set(Array.from({ length: 300 }, (_, i) => feeColor(0.1 * 1.02 ** i)).filter((_, i) => 0.1 * 1.02 ** i <= 30));
  assert.ok(live.size >= 70, `0.1..30 sat/vB: ${live.size} colours`);
});

test('feeBandIndex: the highest band whose threshold is at or below the rate, clamped', () => {
  FEE_BANDS.forEach((b, i) => {
    assert.equal(feeBandIndex(b), i, `a rate on threshold ${b} is band ${i}`);
    if (i > 0) assert.equal(feeBandIndex(b - 1e-6), i - 1, `just under ${b} is the band below`);
  });
  assert.equal(feeBandIndex(0.05), 0, 'under 0.1 sat/vB is band 0');
  assert.equal(feeBandIndex(0.5) > 5, true, 'half a sat/vB is well up the scale');
  for (const r of [0, -3, NaN, Infinity, -Infinity, undefined, null, 'x']) assert.equal(feeBandIndex(r), 0, `rate ${String(r)} -> 0`);
  assert.equal(feeBandIndex(1e9), FEE_BANDS.length - 1, 'above the top: the last band');
  assert.equal(feeBandIndex('12'), feeBandIndex(12), 'numeric strings are rates');
});

test('feeColor: one #rrggbb per band, every neighbour different', () => {
  const colors = FEE_BANDS.map((b) => feeColor(b));
  for (const c of colors) assert.match(c, /^#[0-9a-f]{6}$/);
  for (let i = 1; i < colors.length; i++) assert.notEqual(colors[i], colors[i - 1], `bands ${i - 1} and ${i} differ`);
  // a rate anywhere inside a band is that band's colour
  FEE_BANDS.forEach((b, i) => {
    const next = FEE_BANDS[i + 1] ?? b * 2;
    assert.equal(feeColor(b + (next - b) * 0.7), colors[i]);
  });
  assert.equal(feeColor(-1), colors[0]);
  assert.equal(feeColor(1e7), colors.at(-1));
});

test('feeColor: the ramp runs blue, teal, green, yellow, orange, red, crimson, purple, the hue moving one way only', () => {
  const colors = FEE_BANDS.map((b) => feeColor(b));
  // unwrap: the hue falls from blue (~205) through 0 (red) into the purples (~285 = -75)
  const hues = colors.map(hueOf).map((h) => (h > 240 ? h - 360 : h));
  for (let i = 1; i < hues.length; i++) assert.ok(hues[i] <= hues[i - 1] + 0.5, `hue falls or holds at band ${i} (${hues[i - 1].toFixed(1)} -> ${hues[i].toFixed(1)})`);
  const at = (rate) => hueOf(feeColor(rate));
  assert.ok(at(0.05) > 190 && at(0.05) < 220, 'under 0.1 sat/vB is sky blue');
  assert.ok(at(0.3) > 160 && at(0.3) < 190, 'a few tenths are teal');
  assert.ok(at(1) > 120 && at(1) < 150, '1 sat/vB is green');
  assert.ok(at(3) > 80 && at(3) < 110, 'a few sat/vB are yellow-green');
  assert.ok(at(20) > 35 && at(20) < 60, 'tens of sat/vB are yellow to amber');
  assert.ok(at(60) > 15 && at(60) < 35, 'then orange');
  assert.ok(at(250) < 15 || at(250) > 345, 'hundreds are red');
  const [rt, gt, bt] = rgbOf(colors.at(-1));
  assert.ok(rt > gt && bt > gt && hueOf(colors.at(-1)) > 270 && hueOf(colors.at(-1)) < 320, 'the ceiling is purple');
});

// the factor a shade applies to its band colour, and how far its hue drifted
function shadeVsBand(rate, key) {
  const base = rgbOf(feeColor(rate)), got = rgbOf(feeShade(rate, key));
  const bm = Math.max(...base), gm = Math.max(...got);
  return { k: gm / bm, drift: Math.max(...base.map((v, i) => Math.abs(v / bm - got[i] / gm))) };
}

test('feeShade: darker at the bottom of a band, brighter toward its top, within 0.76..1.34', () => {
  FEE_BANDS.forEach((b, i) => {
    const next = FEE_BANDS[i + 1] ?? b * 2;
    const low = feeShade(b), high = feeShade(b + (next - b) * 0.95);
    assert.match(low, /^#[0-9a-f]{6}$/);
    assert.ok(luma(low) < luma(high), `band ${i}: ${low} darker than ${high}`);
    for (const f of [0, 0.3, 0.6, 0.99]) {
      for (const key of ['', 'a', 'deadbeef', 'aggregate@3,4']) {
        const { k, drift } = shadeVsBand(b + (next - b) * f, key);
        assert.ok(k > 0.76 && k < 1.34, `band ${i} factor ${k.toFixed(3)}`);
        assert.ok(drift <= 0.05, `band ${i}: the hue stays the band's (drift ${drift.toFixed(3)})`);
      }
    }
  });
});

test('feeShade: a small fixed variation per key, and none without one', () => {
  const shades = new Set(Array.from({ length: 40 }, (_, i) => feeShade(7, `tx${i}`)));
  assert.ok(shades.size > 10, `40 equal feerates, ${shades.size} distinct shades`);
  assert.equal(feeShade(7, 'tx1'), feeShade(7, 'tx1'), 'the same key, the same shade');
  assert.equal(feeShade(7), feeShade(7, ''), 'no key means no variation');
  assert.equal(feeShade(7), feeShade(7), 'deterministic');
  assert.notEqual(feeShade(7, 'tx1'), feeShade(7, 'tx2'));
  assert.equal(feeShade(NaN), feeShade(0), 'an unknown rate is shaded as the floor');
});
