// The app, booted for real, spoken to over loopback.
//
// Everything in this file is behaviour that neither a unit test nor scripts/smoke.sh
// used to cover: response headers, cache behaviour, the login throttle, and the two
// drill-down endpoints. The reason it was not covered is recorded in
// test/helpers/http.js — `boot()` had no teardown, so an in-process HTTP test could
// not stop what it started.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { withApp } from './helpers/http.js';
import { computeBuildId } from '../server/http/static.js';

// The bootstrap admin's password is generated by boot() and read back off
// app.bootstrap -- no shared secret through process.env (see helpers/http.js).
// Declared per test via client.adminPassword.

test('the served page is stamped with the build, and says whether it is current', async () => {
  await withApp({}, async ({ client, base }) => {
    const login = await client.login('admin');
    assert.equal(login.status, 200, `login must work: ${JSON.stringify(login.body)}`);

    const res = await client.raw('/', { headers: {} });
    const html = await res.text();
    assert.equal(res.status, 200);

    const csp = res.headers.get('content-security-policy');
    const nonce = /\bnonce-([^';]+)'/.exec(csp)?.[1];
    assert.ok(nonce, `a per-response script nonce is offered: ${csp}`);

    assert.match(html, /data-bmc-build="[\d.]+-[0-9a-f]{10}"/, 'the page carries the build it was served with');
    assert.match(html, /src="\/js\/app\.js\?v=[\d.]+-[0-9a-f]{10}"/, 'the entry module is cache-busted by build');
    assert.match(html, /href="\/css\/app\.css\?v=/, 'the stylesheet too');

    const served = /data-bmc-build="([^"]+)"/.exec(html)[1];
    const build = await client.get(`/api/build?build=${encodeURIComponent(served)}`);
    assert.equal(build.body.matchesClient, true, 'the page can ask whether it is running current code');

    const stale = await client.get('/api/build?build=0.1.0-deadbeef00');
    assert.equal(stale.body.matchesClient, false, 'and the answer is no when it is not');

    // A second request must not reuse the nonce: a constant nonce is an open door
    // with a documentation comment attached.
    const res2 = await client.raw('/');
    const csp2 = res2.headers.get('content-security-policy');
    const nonce2 = /\bnonce-([^';]+)'/.exec(csp2)?.[1];
    assert.notEqual(nonce2, nonce, 'two responses, two nonces');
  });
});

test('the build id tracks the files, which is what makes /api/build answerable live', async () => {
  // The live-digest answer in /api/build is only honest if the digest actually moves
  // when an asset moves. Assert that directly, on a temp tree -- not on public/, which
  // a test must never edit.
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bmc-build-'));
  try {
    fs.mkdirSync(path.join(dir, 'js'), { recursive: true });
    const f = path.join(dir, 'js', 'app.js');
    fs.writeFileSync(f, 'console.log(1);\n');
    const when = new Date(1_700_000_000_000);
    fs.utimesSync(f, when, when);
    const first = await computeBuildId(dir, '0.1.0');

    // Same bytes, same mtime: a redeploy that copies unchanged files must not churn the
    // id, or every reload would look like new code.
    fs.writeFileSync(f, 'console.log(1);\n');
    fs.utimesSync(f, when, when);
    assert.equal(await computeBuildId(dir, '0.1.0'), first, 'an unchanged tree keeps its id');

    // An edit is a different size AND a later mtime: the id must move.
    fs.writeFileSync(f, 'console.log(2); // a fix\n');
    fs.utimesSync(f, new Date(1_700_000_600_000), new Date(1_700_000_600_000));
    const second = await computeBuildId(dir, '0.1.0');
    assert.notEqual(second, first, 'an edited asset changes the build id');
    assert.match(second, /^0\.1\.0-[0-9a-f]{10}$/, 'and it keeps the shape the page stamps');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('/api/build reports the live digest and keeps the boot value separate', async () => {
  await withApp({}, async ({ client }) => {
    await client.login('admin');
    const page = await client.raw('/');
    const served = /data-bmc-build="([^"]+)"/.exec(await page.text())[1];
    const res = await client.get(`/api/build?build=${encodeURIComponent(served)}`);
    assert.equal(res.body.build, served, 'the answer is the build on disk right now, not the one booted');
    assert.equal(res.body.matchesClient, true);
    assert.match(res.body.bootBuild, /^[\d.]+-[0-9a-f]{10}$/, 'what this process loaded at boot stays visible');
  });
});

test('assets revalidate with 304; HTML never does, because it is rewritten', async () => {
  await withApp({}, async ({ client }) => {
    const css = await client.raw('/css/app.css');
    const etag = css.headers.get('etag');
    assert.ok(etag, 'a static asset has an ETag');
    const again = await client.raw('/css/app.css', { headers: { 'If-None-Match': etag } });
    assert.equal(again.status, 304, 'unchanged bytes are not resent: app.css + the three modules are the bulk of a first paint');

    const page = await client.raw('/');
    const pageEtag = page.headers.get('etag');
    const pageAgain = await client.raw('/', { headers: { 'If-None-Match': pageEtag } });
    assert.equal(pageAgain.status, 200,
      'the HTML body is per-response (nonce + build), so a cached body would carry a nonce the new CSP refuses');
    assert.match(pageAgain.headers.get('cache-control') ?? '', /no-cache/);
  });
});

test('login is throttled per address, separately from the username lockout', async () => {
  await withApp({}, async ({ client, app }) => {
    // LoginGuard answers "this username keeps failing". The per-user token bucket
    // cannot apply to a request with no user. What was unmitigated was a slow grind
    // from many addresses, and the cost of each attempt is a scrypt KDF on the
    // request thread.
    const statuses = [];
    for (let i = 0; i < 24; i++) {
      const r = await client.post('/api/login', { username: 'admin', password: `wrong passphrase ${i}` });
      statuses.push(r.status);
    }
    const throttled = statuses.filter((s) => s === 429).length;
    assert.ok(throttled >= 10, `expected the bucket (capacity 10, 0.5/s) to refuse most of 24 attempts, got ${throttled}: ${statuses.join(',')}`);
    assert.ok(statuses.slice(0, 10).every((s) => s === 401 || s === 429), 'early attempts reach the credential check');
    const first = statuses.findIndex((s) => s === 429);
    assert.ok(first >= 5, `the throttle has a real bucket in front of it, not a switch: first 429 at attempt ${first}`);

    const r = await client.post('/api/login', { username: 'admin', password: 'still wrong passphrase' });
    assert.equal(r.status, 429);
    // `kind` is the generic 'api' because this refusal is an HttpError thrown by the
    // route, not the transport-level 429 the server emits for the per-user bucket.
    // `code` is the discriminator the UI keys on.
    assert.equal(r.body.error.code, 'throttled');
    assert.match(r.body.error.message, /retry in \d+s/, 'a refusal has to say when to come back');

    const audit = await client.post('/api/login', {}); // still throttled, shape only
    assert.equal(audit.status, 429);
    const entries = await app.readAudit(50);
    assert.ok(entries.some((e) => e.type === 'login-throttled'), 'a throttle that never appears in the audit trail is invisible');
  });
});

test('a correct password still logs in through the throttle bucket', async () => {
  await withApp({}, async ({ client }) => {
    const r = await client.login('admin');
    assert.equal(r.status, 200);
    assert.ok(r.csrf, 'the CSRF double-submit token is handed to the page that needs it');
    const me = await client.get('/api/me');
    assert.equal(me.body.user.role, 'admin');
    assert.ok(client.cookies().includes('bmcmon_sid'));
  });
});

test('the health and state payloads name the build and the scheme', async () => {
  await withApp({}, async ({ client }) => {
    const h = await client.get('/api/health');
    assert.match(h.body.build, /^[\d.]+-[0-9a-f]{10}$/);
    assert.equal(h.body.scheme, 'http');
    assert.equal(h.body.tls, false, 'health says plainly whether this is plaintext');
    await client.login('admin');
    const s = await client.get('/api/state?series=none');
    assert.match(s.body.app.build, /^[\d.]+-/);
    assert.equal(s.body.app.scheme, 'http');
  });
});
