// TLS: the option, the mistakes, and what each one costs.
//
// Until now this monitor could only serve plaintext HTTP, and the recorded "fix" in
// docs/DEFECTS.md was prose: put a proxy in front, or tunnel. That is a legitimate
// deployment answer, but not a reason to leave the option out — the session cookie
// and every RPC reply cross the LAN in the clear, and this app can read a bitcoin
// node's RPC cookie.
//
// The failures worth guarding are configuration mistakes, because each is worse than
// a crash:
//   * cert without key (or the reverse) silently serving plaintext on a port someone
//     believes is HTTPS;
//   * an expired certificate, which a browser refuses and the dashboard — sitting
//     behind that refusal — cannot report;
//   * TLS on with the Secure cookie off, which reads as "login will not stick".
//
// The end-to-end case generates a throwaway self-signed certificate with openssl and
// SKIPS out loud when the binary is absent. A skipped test that names its reason is
// worth more than a passing test that asserts nothing.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { loadConfig } from '../server/config.js';
import { withApp, logSink } from './helpers/http.js';

const ifaces = { lo: [{ address: '127.0.0.1', family: 'IPv4' }] };
// The bootstrap admin's password is generated by boot() and read back off
// app.bootstrap -- no shared secret through process.env (see helpers/http.js).
// Declared per test via client.adminPassword.

function opensslOrSkip(t) {
  try {
    execFileSync('openssl', ['version'], { stdio: 'pipe' });
    return true;
  } catch {
    t.skip('no openssl on this box, so no certificate can be generated here');
    t.diagnostic('the config-parse cases still ran; only certificate generation needs openssl');
    return false;
  }
}

/** A throwaway self-signed certificate, 20 days: straddles the 14-day warning. */
function selfSigned(dir, days = 20) {
  const cert = path.join(dir, 'cert.pem');
  const key = path.join(dir, 'key.pem');
  execFileSync('openssl', ['req', '-x509', '-newkey', 'rsa:2048', '-nodes',
    '-keyout', key, '-out', cert, '-days', String(days), '-subj', '/CN=bmcmon-test'], { stdio: 'pipe' });
  return { cert, key };
}

function cfgWith(tls, dir) {
  const file = path.join(dir, 'c.json');
  fs.writeFileSync(file, JSON.stringify({ server: { tls } }));
  return file;
}

test('defaults load with TLS off and say the scheme is http', () => {
  const cfg = loadConfig({ configFile: '/nonexistent.json', ifaces });
  assert.equal(cfg.tls, false);
  assert.equal(cfg.server.tls.cert, null);
  assert.equal(cfg.auth.secureCookie, false, 'off by default; boot forces it on when TLS is on');
});

test('cert or key alone stops the boot, naming which one is missing', (t) => {
  if (!opensslOrSkip(t)) return;
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bmcmon-tls-'));
  try {
    const { cert, key } = selfSigned(dir);
    assert.throws(() => loadConfig({ configFile: cfgWith({ cert, key: null }, dir), ifaces }),
      /needs BOTH cert and key \(got cert only\)/);
    assert.throws(() => loadConfig({ configFile: cfgWith({ cert: null, key }, dir), ifaces }),
      /needs BOTH cert and key \(got key only\)/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('an unreadable cert or key is a config error, not a listen-time surprise', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bmcmon-tls-'));
  try {
    assert.throws(
      () => loadConfig({ configFile: cfgWith({ cert: path.join(dir, 'nope.pem'), key: path.join(dir, 'nope-key.pem') }, dir), ifaces }),
      /server\.tls\.cert cannot be read/,
    );
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('a certificate that is not a certificate is refused at load', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bmcmon-tls-'));
  try {
    fs.writeFileSync(path.join(dir, 'cert.pem'), '-----BEGIN CERTIFICATE-----\nnot base64 at all\n-----END CERTIFICATE-----\n');
    fs.writeFileSync(path.join(dir, 'key.pem'), 'x');
    assert.throws(
      () => loadConfig({ configFile: cfgWith({ cert: path.join(dir, 'cert.pem'), key: path.join(dir, 'key.pem') }, dir), ifaces }),
      /not a parseable X\.509/,
    );
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('an expired certificate stops the boot; a near-expiry one warns', (t) => {
  if (!opensslOrSkip(t)) return;
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bmcmon-tls-'));
  try {
    const { cert, key } = selfSigned(dir, 20);
    const file = cfgWith({ cert, key }, dir);

    // A real certificate and a clock in the future: the branch is exercised without
    // shipping a certificate that will change this test's behaviour on a Tuesday.
    assert.throws(() => loadConfig({ configFile: file, ifaces, now: Date.now() + 400 * 86_400_000 }),
      /expired .*browser will refuse/);

    // Today: 20 days out, outside the 14-day window, so it boots quietly.
    const ok = loadConfig({ configFile: file, ifaces });
    assert.equal(ok.tls, true);
    assert.equal(ok.__tlsExpiring, undefined, '20 days of validity is not a warning');
    assert.equal(ok.server.tls.selfSigned, true, 'a LAN box with no issuer: expect a browser warning');
    assert.match(ok.server.tls.fingerprint, /^[0-9A-F:]+$/, 'the fingerprint is logged so a cert swap is visible');

    // Inside the window: boots, with something to say.
    const soon = loadConfig({ configFile: file, ifaces, now: Date.now() + 10 * 86_400_000 });
    assert.equal(soon.tls, true);
    assert.match(soon.__tlsExpiring, /expires/, 'and the boot line carries it');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('with TLS on: HTTPS serves, HTTP does not, the cookie is Secure and HSTS is sent', async (t) => {
  if (!opensslOrSkip(t)) return;
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'bmcmon-tls-'));
  try {
    const { cert, key } = selfSigned(dir);
    // The one env var this test must own itself: Node's fetch has no per-request
    // dispatcher reachable from builtins, so verification of a throwaway self-signed
    // cert is disabled for the duration of THIS test only, and put back in finally.
    // The helper deliberately touches no env (Node runs a file's tests concurrently,
    // so shared process.env is a cross-test race). What is under test is the
    // handshake, the headers and the cookie flags -- not the trust chain, which a LAN
    // box does not have.
    const hadTls = process.env.NODE_TLS_REJECT_UNAUTHORIZED;
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
    try {
    await withApp({
      tlsFiles: { cert, key },
      log: logSink(),
    }, async ({ client, base, app }) => {
      assert.equal(app.tls, true, 'the app knows it is encrypted');
      assert.match(app.log.text(), /TLS on \(fingerprint [0-9A-F:]{17}/,
        'the boot line names the fingerprint: a silent cert swap is otherwise invisible');
      assert.match(app.log.text(), /self-signed/, 'and says a browser warning is expected');
      assert.equal(app.cfg.auth.secureCookie, true, 'and the cookie follows automatically');

      const res = await client.raw('/api/health');
      assert.equal(res.status, 200);
      assert.equal(res.headers.get('strict-transport-security'), 'max-age=172800');
      assert.equal((await res.json()).scheme, 'https', 'health reports the scheme it answered on');

      const login = await client.login('admin');
      assert.equal(login.status, 200);
      const setCookies = (await client.raw('/api/login', { method: 'POST', body: { username: 'admin', password: client.adminPassword } })).headers.getSetCookie();
      assert.ok(setCookies.some((c) => /bmcmon_sid=/.test(c) && /\bSecure\b/.test(c)),
        `a Secure cookie over TLS: ${setCookies.join(' | ')}`);

      assert.match((await client.get('/api/build')).body.scheme, /^https$/);
      // Plain HTTP against the TLS listener must fail, not answer.
      await assert.rejects(() => fetch(base.replace('https://', 'http://') + '/api/health'),
        'plaintext against a TLS listener is a failure, never a fallback');
    });
    } finally {
      if (hadTls === undefined) delete process.env.NODE_TLS_REJECT_UNAUTHORIZED;
      else process.env.NODE_TLS_REJECT_UNAUTHORIZED = hadTls;
    }
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('without TLS the boot warns, in words', async () => {
  // Captured through boot()'s log seam rather than by replacing process.stdout.write:
  // the hijack raced the test runner's own TAP writer and ate the reported results of
  // unrelated tests in the same file. Observing a warning must not be allowed to hide
  // other observations -- the same class of bug as a log line that hides a fault.
  const log = logSink();
  await withApp({ log }, async ({ app }) => {
    assert.equal(app.tls, false);
    const out = log.text();
    assert.match(out, /warn serving HTTP, not HTTPS/,
      'the plaintext default has to be loud at boot, not a footnote in a README nobody opens');
    assert.match(out, /server\.tls\.cert/, 'and it names what to set, not just what is wrong');
    assert.ok(!/TLS on/.test(out), 'no claim of encryption that is not happening');
  });
});
