#!/usr/bin/env node
// Container entrypoint for the Umbrel package (umbrel/README.md).
//
// It does one thing before handing over to the server: render local.json from the
// environment the Umbrel `bitcoin` app exports. BlockYard reads the node's RPC
// credentials from a config FILE only -- there is no BLOCKYARD_RPC_USER and no
// BLOCKYARD_RPC_PASSWORD (server/config.js) -- so something has to write that file, and
// env is all a container is given.
//
// Rendered on EVERY start, not just the first. Umbrel can change the node's RPC password
// between restarts; a file written once would then be stale and the monitor would sit
// there unauthorised. The cost is that hand edits do not survive, which is the right
// answer for a file that is derived.
//
// What it does NOT touch: blockyard.json beside it (the display settings people choose in
// the UI, which the server keeps next to the config file), state/ (users, sessions,
// history) and index/. Those are the app's own and last as long as the data volume does.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');

/** Umbrel's network names are not Core's chain names, and `chainHint` is Core's. */
export const CHAINS = Object.freeze({ mainnet: 'main', testnet: 'test', signet: 'signet', regtest: 'regtest' });

/** Where the node's data directory is mounted, read-only, in the container. */
export const MOUNT = '/var/lib/bitcoind';

// The address index reads <datadir>/blocks. On mainnet blocks/ sits directly under the
// data directory; on every other network it is one level down, in the chain's own subdir.
// Pointing datadir at the right level is what lets the index be built on any of them.
const SUBDIR = Object.freeze({ test: 'testnet3', signet: 'signet', regtest: 'regtest' });

/**
 * The local.json text for this environment.
 *
 * Throws with the names of whatever the bitcoin app did not export, rather than writing a
 * config that would aim the monitor at nothing.
 */
export function renderConfig(env = process.env, templateFile = path.join(HERE, 'local.json.template')) {
  const chain = CHAINS[env.APP_BITCOIN_NETWORK || 'mainnet'] || 'main';
  const vars = {
    ...env,
    NODE_CHAIN: chain,
    NODE_DATADIR: chain === 'main' ? MOUNT : path.join(MOUNT, SUBDIR[chain]),
    NODE_LABEL: chain === 'main' ? 'Bitcoin Core' : `Bitcoin Core (${chain})`,
  };
  const missing = [];
  // ${NAME} substitution, JSON-escaped. An RPC password is generated by Umbrel and can
  // hold a quote or a backslash; pasting it in raw would produce a config file that does
  // not parse, and that failure would look like a credentials problem.
  const text = fs.readFileSync(templateFile, 'utf8').replace(/\$\{([A-Z0-9_]+)\}/g, (_, name) => {
    const v = vars[name];
    if (v === undefined || v === '') { missing.push(name); return ''; }
    return JSON.stringify(String(v)).slice(1, -1);
  });
  if (missing.length) {
    const err = new Error(`unset in the environment: ${[...new Set(missing)].join(', ')}`);
    err.missing = [...new Set(missing)];
    throw err;
  }
  JSON.parse(text); // a template typo stops here, not four layers into the config load
  return text;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === fs.realpathSync(process.argv[1]);
if (isMain) {
  const out = process.env.BLOCKYARD_CONFIG || '/app/data/local.json';
  let text;
  try {
    text = renderConfig();
  } catch (err) {
    // Loud, and in the app's own logs: a missing APP_BITCOIN_* means the bitcoin app is
    // not running, or the dependency was dropped from the manifest.
    console.error(`blockyard: cannot write ${out} -- ${err.message}`);
    console.error('blockyard: the Umbrel "bitcoin" app exports those; check that it is installed and running.');
    process.exit(1);
  }
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, text, { mode: 0o600 });

  console.log(`blockyard: wrote ${out} for ${process.env.APP_BITCOIN_NODE_IP}:${process.env.APP_BITCOIN_RPC_PORT}`);

  // Hand the server the argv it expects. server/main.js boots only when it decides it is
  // being run directly, which it does by comparing argv[1] with its own path -- so an
  // import from here, with argv[1] still naming this file, would load the module and
  // start nothing at all. bin/blockyard.js splices argv for the same reason.
  const main = path.join(ROOT, 'server', 'main.js');
  process.argv.splice(1, 1, main);
  await import(main);
}
